# EVENT ENDPOINTS

### 
GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "THE DREAM SHOW",
    "description": "Cool",
    "date": "2024-08-01T20:00:00",
    "price": 200
}

###
@eventId = {{ createEvent.response.body.id }}

### 
GET http://localhost:3000/events/{{ eventId }}

###
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
    "name": "THE DREAM SHOW",
    "description": "Very cool",
    "date": "2024-08-01T17:00:00",
    "price": 200
}

###
DELETE http://localhost:3000/events/{{ eventId }}

# SPOT ENDPOINTS

### 
GET http://localhost:3000/events/{{ eventId }}/spots

###
# @name createSpot
POST http://localhost:3000/events/{{ eventId }}/spots
Content-Type: application/json

{
    "name": "A1"
}

###
@spotId = {{ createSpot.response.body.id }}

### 
GET http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}

###
PATCH http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}
Content-Type: application/json

{
    "name": "B1",
    "status": "reserved"
}

###
DELETE http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}

# RESERVE ENDPOINT

###
@spotName = {{ createSpot.response.body.name }}

###
POST http://localhost:3000/events/{{ eventId }}/reserve
Content-Type: application/json

{
    "spots": ["{{ spotName }}"],
    "ticketKind": "full",
    "email": "example@email.com"
}